/* @flow */

import React from "react";
import {
    AppRegistry,
    StyleSheet,
    Text,
    View,
    ScrollView
} from 'react-native';
import MainContent from "../../../common/ui/MainContent";

const Home = React.createClass({

    propTypes : {},

    render() {
        return (
            <MainContent>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
                <View>
                    <Text>Home!</Text>
                </View>
            </MainContent>
        );
    }

});

export default Home;
